# Generated by Django 4.1.7 on 2023-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='issues_watched',
            field=models.ManyToManyField(blank=True, to='issues.issue'),
        ),
    ]
