# Generated by Django 4.1.7 on 2023-04-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_user_issues_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
