# Generated by Django 4.1.7 on 2023-04-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=60)),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('delete', 'Delete'), ('edit', 'Edit')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.issue')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='logs',
            field=models.ManyToManyField(blank=True, to='issues.log'),
        ),
    ]
