# Generated by Django 4.1.7 on 2023-04-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_delete_issueattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='issues_watched',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
