# Generated by Django 4.1.7 on 2023-04-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_remove_user_groups_remove_user_issues_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
