# Generated by Django 4.1.7 on 2023-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_alter_issue_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
