# Generated by Django 4.1.7 on 2023-04-11 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_alter_issue_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
