# Generated by Django 4.1.7 on 2023-04-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_issue_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='deadline',
            new_name='dead_line',
        ),
    ]
