# Generated by Django 4.1.7 on 2023-04-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_rename_deadline_issue_dead_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='dead_line',
            new_name='deadline',
        ),
    ]
