# Generated by Django 4.1.7 on 2023-04-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_alter_issue_updated_at'),
        ('issues', '0016_alter_issue_deadline'),
    ]

    operations = [
    ]
