# Generated by Django 4.1.7 on 2023-04-13 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0017_merge_20230412_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formerSubject', models.CharField(blank=True, max_length=60, null=True)),
                ('formerContent', models.TextField(blank=True, max_length=280, null=True)),
                ('formerType', models.CharField(blank=True, choices=[('B', 'Bug'), ('Q', 'Question'), ('E', 'Enhancement')], max_length=2, null=True)),
                ('formerSeverity', models.CharField(blank=True, choices=[('W', 'Whishlist'), ('M', 'Minor'), ('N', 'Normal'), ('I', 'Important'), ('C', 'Critical')], max_length=2, null=True)),
                ('formerPriority', models.CharField(blank=True, choices=[('L', 'Low'), ('N', 'Normal'), ('H', 'High')], max_length=2, null=True)),
                ('latterSubject', models.CharField(blank=True, max_length=60, null=True)),
                ('latterContent', models.TextField(blank=True, max_length=280, null=True)),
                ('latterType', models.CharField(blank=True, choices=[('B', 'Bug'), ('Q', 'Question'), ('E', 'Enhancement')], max_length=2, null=True)),
                ('latterSeverity', models.CharField(blank=True, choices=[('W', 'Whishlist'), ('M', 'Minor'), ('N', 'Normal'), ('I', 'Important'), ('C', 'Critical')], max_length=2, null=True)),
                ('latterPriority', models.CharField(blank=True, choices=[('L', 'Low'), ('N', 'Normal'), ('H', 'High')], max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.ManyToManyField(to='attachments.issueattachment')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='issues.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
