# Generated by Django 4.1.7 on 2023-04-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_log_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='deadline',
            new_name='issue_deadline',
        ),
    ]
